version: 2.1
defaults: &defaults
  machine:
    image: ubuntu-2004:202104-01

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: wget https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
      - run: chmod +x lein && sudo mv lein /usr/local/bin
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository ppa:swi-prolog/stable
      - run: sudo apt-get install swi-prolog swi-prolog-java
      - run: mkdir resources && ln -s /usr/share/java/jpl.jar /usr/lib/x86_64-linux-gnu/jni/libjpl.so resources/
      - run: lein test

  publish:
    <<: *defaults
    steps:
      - checkout
      - run: wget https://github.com/babashka/babashka/releases/download/v0.4.3/babashka-0.4.3-linux-amd64-static.tar.gz && tar -xf babashka-0.4.3-linux-amd64-static.tar.gz
      - run: curl https://raw.githubusercontent.com/mauricioszabo/clj-lib-deployer/master/deploy-lein.bb -o deploy
      - run: lein change :profiles:dev:jvm-opts empty
      - run: export TAG=$CIRCLE_TAG && ./bb deploy

workflows:
  version: 2
  default-workflow:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^v.+/

      - publish:
          context: Clojure Libs
          requires:
            - test
          filters:
            tags:
              only:
                - /^v.+/
            branches:
              only:
                - master
