version: 2.1
defaults: &defaults
  docker:
    - image: circleci/clojure:openjdk-11-lein-node

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-add-repository ppa:swi-prolog/stable
      - run: sudo apt-get install swi-prolog-java
      - run: mkdir resources && cp /usr/share/java/jpl.jar /usr/lib/x86_64-linux-gnu/jni/libjpl.so resources/
      - run: lein test

  # publish:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - run: ./scripts/deploy.sh

workflows:
  version: 2
  default-workflow:
    jobs:
      - test:
          filters:
            tags:
              only:
                - /^v.+/

      # - publish:
      #     context: Clojure Libs
      #     requires:
      #       - test
      #     filters:
      #       tags:
      #         only:
      #           - /^v.+/
      #       branches:
      #         only:
      #           - master
